version: "3.8"

services:
  app:
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:80" # External port 8080 → internal Nginx port 80
      # - "3000:3000" # Optional: direct Next.js access
      # - "4000:4000" # Optional: WebSocket access
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_HOST: https://preferably-in-teal.ngrok-free.app
      NEXT_PUBLIC_SERVER_PORT: 4000
      NEXT_PUBLIC_SERVER_SOCKET_URL: wss://preferably-in-teal.ngrok-free.app/backend/ws
      NEXT_PUBLIC_SERVER_URL: https://preferably-in-teal.ngrok-free.app/backend

    restart: unless-stopped
